image: docker:latest
services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
- build
- package
- deploy

gradle-build:
  image: java:8
  stage: build
  script:
  - ./gradlew build
  artifacts:
    paths:
    - build/*
  only:
  - master

docker-build:
  stage: package
  script:
  - docker build -t registry.gitlab.com/bitemii/order-service:$CI_COMMIT_SHA .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/bitemii/order-service:$CI_COMMIT_SHA

deploy-dev:
  image: google/cloud-sdk
  stage: deploy
  script:
  - echo "$GOOGLE_BITEMII_KEY" > key.json
  - gcloud auth activate-service-account --key-file key.json
  - gcloud config set compute/zone us-central1-a
  - gcloud config set project genuine-hold-216506
  - gcloud container clusters get-credentials bitemii-dev
  - kubectl config view
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh
  - chmod 700 get_helm.sh
  - ./get_helm.sh --version v2.10.0
  - helm init --client-only
  - helm repo add stable https://kubernetes-charts.storage.googleapis.com/
  - helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
  - helm repo update
  - helm upgrade order-service ./order-service/ --set image.tag=$CI_COMMIT_SHA
  only:
  - master

